server:
    port: 19000

logging:
    file:
        path: .\logs\
        max-size: 500MB
        max-history: 10
    level: 
        # root: debug   # root를 debug로 하면 많은 정보가 나온다.
        com.woopi.project.*: debug    # 패키지별 log레벨 설정

spring:
    application:
        name: wp-project-api-gateway
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    cloud:
        gateway:
            default-filters:   
                - name: GlobalFilter    #GlobalFilter.java의 기본 필터 설정
                  args:
                    baseMessage: ApiGateway Service Global Filter Test
                    preLogger: true
                    postLogger: true
            routes:
                - id : wp-project-verification-service
                  # 랜덤 포트에 호출하기 위한 설정 'wp-project-verification-server'는 유레카에 등록된 서비스명
                  # uri는 underline을 지원하지 않는다.(중요!!!)
                  # uri: lb://wp-project-verification-server (대문자로 해야하나?) 
                  uri: http://localhost:19001/
                  predicates:
                    - Path=/verification/**
                  filters:
                    - CustomFilter  # first-service에만 해당하는 필터 설정
                    - AddRequestHeader=request_header_key_1, request_header_value_1     # AddRequestHeader로 requestHeader값 설정
                    - AddRequestHeader=request_header_key_2, request_header_value_2
                    - AddResponseHeader=response_header_key_1, response_header_value_1  # AddResponseHeader로 responseHeader값 설정
                    - AddResponseHeader=response_header_key_2, response_header_value_2
                # - id: second_service
                #   predicates:
                #     - Path=/second_service/**
                #   uri: http://localhost:8082
                #   filters:
                #     - AddRequestHeader=second_request_header_key, second_request_header_value_yml
                #     - AddResponseHeader=second_response_header_key, second_response_header_value_yml
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
            # eureka-discovery-server은 브릿지에 연결된 컨테이너 이름
            # [참고] https://woopi1087.tistory.com/88
            defaultZone: http://localhost:18761/eureka

    
        
        

